name: Model Training Workflow

on:
  push:
    paths:
      - 'dataset_preprocessed/**'
      - 'MLProject/**'
      - '.github/workflows/**'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Train Model (MLflow Project)
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local --experiment-name "Loan Prediction Experiment"
